// Template for environment.ts — generated by `pnpm set-env:dev`
// 1. Copy .env.example → .env.local
// 2. Fill in your Supabase credentials
// 3. Run: pnpm set-env:dev
export const environment = {
  production: false,
  supabaseUrl: '',
  supabaseAnonKey: '',
};
